name: Build and Release HisaabFlow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate configs from templates
        shell: bash
        run: |
          cd configs
          for template in *.conf.template; do
            if [ -f "$template" ]; then
              conf_file="${template%.template}"
              echo "Converting $template -> $conf_file"
              cp "$template" "$conf_file"
            fi
          done
          ls -la *.conf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python (for bundle preparation)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Prepare Python runtime bundle
        working-directory: frontend
        run: npm run prepare-python

      - name: Build React app
        working-directory: frontend
        run: npm run build

      - name: Build Electron app (Linux)
        if: matrix.platform == 'linux'
        working-directory: frontend
        run: npm run build && npx electron-builder --linux --publish never

      - name: Build Electron app (macOS)
        if: matrix.platform == 'mac'
        working-directory: frontend
        run: npm run build && npx electron-builder --mac --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hisaabflow-${{ matrix.platform }}
          path: |
            frontend/dist/*.AppImage
            frontend/dist/*.dmg
          retention-days: 30
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
        
      - name: List downloaded artifacts (debug)
        run: |
          echo "Downloaded artifacts structure:"
          find ./artifacts -type f -name "*.AppImage" -o -name "*.dmg" || echo "No build artifacts found"
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/**/*.AppImage
            ./artifacts/**/*.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: false
